name: CI/CD Pipeline for ExpenseTracker

on:
  push:
    branches: ["main"]

jobs:
  build-test-store-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore & Build
      run: |
        dotnet restore
        dotnet publish -c Release -o out

    # If using Sonar â€” otherwise you can remove this step
    - name: SonarQube Scan
      run: |
        docker run --rm \
        --network host \
        -v ${{ github.workspace }}:/src \
        sonarsource/sonar-scanner-cli \
        -Dsonar.projectKey=ExpenseTracker \
        -Dsonar.sources=/src \
        -Dsonar.host.url=${{ secrets.SONAR_HOST }} \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      continue-on-error: true

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/expensetracker:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/expensetracker:latest

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/expensetracker:latest
          docker stop expensetracker || true
          docker rm expensetracker || true
          docker run -d -p 8080:8080 --name expensetracker ${{ secrets.DOCKERHUB_USERNAME }}/expensetracker:latest
